### PR TITLE
Storage module tests

### PR DESCRIPTION
**Pull request by abdlquadri**
# Storage Module Integration Tests

## Description

Adds 

1. `integration.BaseStorageITTest`, 

2. `integration.MemoryStorageITTest` and 
3. `integration.RedisStorageITTest`

in order to verify storage module functions in both `spp.platform.storage.MemoryStorage` and `spp.platform.storage.RedisStorage`

### CODE REVIEW

**Comment by abdlquadri** [comment]
Hi @BFergerson , couple of questions:

1. After storage.addDeveloper("dev_1", "token_1") , storage.getDevelopers()[1] returns a Developer instance with developer.accessToken=null. I see a way to resolve this but I thought it is by design not to return the token for security reasons. Right?
2. For the redis Impl., storage.getDevelopers()[1].id returns "system" while for the memory Impl. I got the ID of developer I added. is this OK?
3. For memory, I see that we don't need this line: storage.init(vertx, JsonObject().put("host", "localhost").put("port", 6379)) for it to work. It makes sense since memory doesn't connect via port. So I removed it from the memory test.

**Comment by BFergerson** [comment]
Apologies for the delay. Computer trouble.

1. That's correct. Access tokens are not kept in memory to avoid accidentally leaking credentials.
2. The memory and Redis storage implementations should work exactly the same. This issue stems from the fact that other integration tests are using the Redis storage and not the memory storage. To fix this you should call `SourceStorage.reset()` before all tests. To better enforce testing both storages the same you should make a base class `StorageITTest` and have `MemoryStorageITTest` and `RedisStorageITTest` extend it.
3. That's already been removed.

**Comment by abdlquadri** [comment]
@BFergerson I think the PR is ready. Kindly review.
Please note that I added a [reset for client accessors](https://github.com/sourceplusplus/live-platform/pull/490/commits/f82c7608ee22ac58fb5e871a730cc2fb9243565f#diff-d79674c8eceb19ae98fc671fc15fc875d057391e08684d7b46716782f1910390R138)

Which module do you think is best next?

**Comment by BFergerson** [comment]
Thanks for adding client access to reset. The next module is going to be processor/live-instrument. I'm working on the new design for tests right now. I'll create an issue and tag you as soon as I'm done.

**Pull request merged**
